### ISSUE TITLE
Camera Doesn't Rotate Player to Cinemachine Camera Rotation

### ISSUE THREAD

**Issue by parkerhams** [parkerhams/SystemsStudyGame#4]
Scene: MovementTest
Branch: player-rotation
Description:
Setting the player's rotation on space bar input does not fully move or rotate the player. The code itself worked when I'm working with a non-cinemachine camera - in that, in another scene called NoCinemachine_Test I've used the same script and player prefab and just used the main camera, and on play I rotate the camera and hit the space bar and the player's rotation is then set to the camera rotation.
I am currently researching more about cinemachine to be sure I'm calling the correct components and can understand it more thoroughly in order to set the player's rotation to a FreeLookCamera.

**Comment by dantogno** [comment]
I looked into this.
1. The script is indeed rotating the player character correctly.
1. The problem is that the camera is also rotating based on the player character's rotation, which makes it look bad.
   - You can observe this by rotating the player in the inspector and observing the camera moving.
1. So the solution is to not have the camera rotate based on the player character's rotation. (My understanding of what you want is for the camera to only rotate based on player-input. Then the player character rotates based on the camera when the player presses the move button.)
1. Because we didn't write the built-in cinemachine script for free look cam, we are unsure of why / how it's rotating the camera based on the player character's rotation. 
    - One solution is to write our own script that doesn't rotate the camera based on the player character's rotation. I don't like this solution because it is a lot of work and there are many things about the current free-look script that are useful for us.
   - A preferred solution is to work with the settings of the cinemachine camera script we have and try to find one that doesn't rotate based on the follow target's rotation.
      - I've done some research and it looks like the **Orbits > Binding Mode** settings in the inspector for the free look cam script might help fix the problem. Try using "world space"
![image](https://user-images.githubusercontent.com/3150710/53977090-dd7de700-40cd-11e9-9283-e7f700dbc453.png)

Once you fix this you will discover more issues, but we can tackle them one by one. Main thing is to figure out the behavior you want as a designer and communicate it clearly so we can figure out how to get there :)
